params:
  input_shape: (64,64,3)
  target_size: (64,64)
  epochs: 2
  batch_size: 32
  loss_function: categorical_crossentropy
  metrics: [accuracy]
  optimizer: adam  
  validation_steps: 1000
  steps_per_epoch: 2000
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  train_path: 'flower_photos/train'
  test_path: 'flower_photos/validation'
